###
### Cookie cutter parameters
input_catalog:
  hdu: 2
  x_tag: 'XWIN_IMAGE'
  y_tag: 'YWIN_IMAGE'
  ra_tag: 'ALPHAWIN_J2000'
  dec_tag: 'DELTAWIN_J2000'
  ra_units: 'deg'
  dec_units: 'deg'

# Box size for all images
box_size: 61

# This is actually called ERR, not weight, shruggie emoticon
weight_image:
  hdu: 4

err_image:
  hdu: 2

# Science exposure is usually 0th extension
sci_image:
  hdu: 1

# Location of SEx/PIFF/PSFEx config files
configdir: '/Users/j.mccleary/Research/jwst_cosmos/cweb_psf/astro_config/'

# Output directory
outdir: '/Users/j.mccleary/Research/jwst_cosmos/real_data/Apr2023/working2/'

# Reference an external star catalog or parameters
star_params:
  truthstars:
  param_file: '/Users/j.mccleary/Research/jwst_cosmos/cweb_psf/configs/Jan2023_star_params.yaml'
